/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryapp.client.ui.form;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import libraryapp.client.controller.Controller;
import libraryapp.common.domain.UserProfile;
import libraryapp.client.session.ApplicationSession;
import libraryapp.client.ui.form.loan.LoanAddForm;
import libraryapp.client.ui.form.loan.LoanSearchForm;

/**
 *
 * @author Branislav Vujanov
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLibrary = new javax.swing.JMenu();
        LoanMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblUser.setText("jLabel1");

        menuLibrary.setText("Zaduzenja");

        LoanMenuItem.setText("Pregled zaduzenja");
        LoanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanMenuItemActionPerformed(evt);
            }
        });
        menuLibrary.add(LoanMenuItem);

        jMenuItem1.setText(" Novo zaduzenje");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuLibrary.add(jMenuItem1);

        jMenuBar1.add(menuLibrary);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 403, Short.MAX_VALUE)
                .addComponent(lblUser))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanMenuItemActionPerformed
        try {
            new LoanSearchForm(this, true).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Konekija je prekinuta od strane servera!\nProgram ce prekinuti sa radom!", "Communication error", ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_LoanMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          try {
            new LoanAddForm(this, true).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Konekija je prekinuta od strane servera!\nProgram ce prekinuti sa radom!", "Communication error", ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Controller.getInstance().logout();
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoanMenuItem;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu menuLibrary;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        UserProfile user = ApplicationSession.getInstance().getLoginUser();
        lblUser.setText("Ulogovani korisnik: " + user.getFirstName() + " " + user.getLastName() + " , status: " + user.getUserRole());

        //samo zaposleni imaju pristup evidenciji o zaduzenjima, kao i njihovom kreiranju i ponistavanju
        if (user.getUserRole().toString().equals("USER")) {
            menuLibrary.setEnabled(false);
        }

    }
}
