/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibraryapp.ui.form;

import mylibraryapp.domain.UserProfile;
import mylibraryapp.session.ApplicationSession;
import mylibraryapp.ui.form.author.AuthorAddForm;
import mylibraryapp.ui.form.author.AuthorEditForm;
import mylibraryapp.ui.form.author.AuthorSearchForm;
import mylibraryapp.ui.form.book.BookAddForm;
import mylibraryapp.ui.form.book.BookEditForm;
import mylibraryapp.ui.form.book.BookSearchForm;
import mylibraryapp.ui.form.loan.LoanAddForm;
import mylibraryapp.ui.form.loan.LoanSearchForm;
import mylibraryapp.ui.form.user.profile.UserProfileAddForm;
import mylibraryapp.ui.form.user.profile.UserProfileSearchForm;

/**
 *
 * @author Branislav Vujanov
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLibrary = new javax.swing.JMenu();
        LoanMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuBook = new javax.swing.JMenu();
        BookPreviewMenuItem = new javax.swing.JMenuItem();
        BookAddMenuItem = new javax.swing.JMenuItem();
        BookEditMenuItem = new javax.swing.JMenuItem();
        menuAuthor = new javax.swing.JMenu();
        AuthorPreviewMenuItem = new javax.swing.JMenuItem();
        AuthorAddMenuItem = new javax.swing.JMenuItem();
        AuthorEditMenuItem = new javax.swing.JMenuItem();
        menuUserProfile = new javax.swing.JMenu();
        UserProfilePreviewMenuItem = new javax.swing.JMenuItem();
        UserProfileAddMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblUser.setText("jLabel1");

        menuLibrary.setText("Zaduzenja");

        LoanMenuItem.setText("Pregled zaduzenja");
        LoanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanMenuItemActionPerformed(evt);
            }
        });
        menuLibrary.add(LoanMenuItem);

        jMenuItem1.setText(" Novo zaduzenje");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuLibrary.add(jMenuItem1);

        jMenuBar1.add(menuLibrary);

        menuBook.setText("Knjige");

        BookPreviewMenuItem.setText("Pregled knjiga");
        BookPreviewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPreviewMenuItemActionPerformed(evt);
            }
        });
        menuBook.add(BookPreviewMenuItem);

        BookAddMenuItem.setText("Dodaj knjigu");
        BookAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAddMenuItemActionPerformed(evt);
            }
        });
        menuBook.add(BookAddMenuItem);

        BookEditMenuItem.setText("Izmeni podatke o knjizi");
        BookEditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookEditMenuItemActionPerformed(evt);
            }
        });
        menuBook.add(BookEditMenuItem);

        jMenuBar1.add(menuBook);

        menuAuthor.setText("Autori");

        AuthorPreviewMenuItem.setText("Pregled autora");
        AuthorPreviewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorPreviewMenuItemActionPerformed(evt);
            }
        });
        menuAuthor.add(AuthorPreviewMenuItem);

        AuthorAddMenuItem.setText("Dodaj autora");
        AuthorAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorAddMenuItemActionPerformed(evt);
            }
        });
        menuAuthor.add(AuthorAddMenuItem);

        AuthorEditMenuItem.setText(" Izmeni podatke o autoru");
        AuthorEditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorEditMenuItemActionPerformed(evt);
            }
        });
        menuAuthor.add(AuthorEditMenuItem);

        jMenuBar1.add(menuAuthor);

        menuUserProfile.setText("Korisnici");

        UserProfilePreviewMenuItem.setText("Pregled korisnika");
        UserProfilePreviewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfilePreviewMenuItemActionPerformed(evt);
            }
        });
        menuUserProfile.add(UserProfilePreviewMenuItem);

        UserProfileAddMenuItem.setText("Dodaj novog korisnika");
        UserProfileAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfileAddMenuItemActionPerformed(evt);
            }
        });
        menuUserProfile.add(UserProfileAddMenuItem);

        jMenuBar1.add(menuUserProfile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 403, Short.MAX_VALUE)
                .addComponent(lblUser))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthorPreviewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorPreviewMenuItemActionPerformed
        new AuthorSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_AuthorPreviewMenuItemActionPerformed

    private void BookPreviewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPreviewMenuItemActionPerformed
        new BookSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_BookPreviewMenuItemActionPerformed

    private void UserProfilePreviewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfilePreviewMenuItemActionPerformed
        new UserProfileSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_UserProfilePreviewMenuItemActionPerformed

    private void AuthorAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorAddMenuItemActionPerformed
        new AuthorAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_AuthorAddMenuItemActionPerformed

    private void UserProfileAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfileAddMenuItemActionPerformed
        new UserProfileAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_UserProfileAddMenuItemActionPerformed

    private void BookAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAddMenuItemActionPerformed
        new BookAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_BookAddMenuItemActionPerformed

    private void LoanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanMenuItemActionPerformed
        new LoanSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_LoanMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new LoanAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AuthorEditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorEditMenuItemActionPerformed
        new AuthorEditForm(this, true).setVisible(true);
    }//GEN-LAST:event_AuthorEditMenuItemActionPerformed

    private void BookEditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookEditMenuItemActionPerformed
        new BookEditForm(this, true).setVisible(true);
    }//GEN-LAST:event_BookEditMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AuthorAddMenuItem;
    private javax.swing.JMenuItem AuthorEditMenuItem;
    private javax.swing.JMenuItem AuthorPreviewMenuItem;
    private javax.swing.JMenuItem BookAddMenuItem;
    private javax.swing.JMenuItem BookEditMenuItem;
    private javax.swing.JMenuItem BookPreviewMenuItem;
    private javax.swing.JMenuItem LoanMenuItem;
    private javax.swing.JMenuItem UserProfileAddMenuItem;
    private javax.swing.JMenuItem UserProfilePreviewMenuItem;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu menuAuthor;
    private javax.swing.JMenu menuBook;
    private javax.swing.JMenu menuLibrary;
    private javax.swing.JMenu menuUserProfile;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        UserProfile user = ApplicationSession.getInstance().getLoginUser();   
        lblUser.setText("Ulogovani korisnik: " + user.getFirstName() + " " + user.getLastName() + " , status: " + user.getUserRole());

        if (user.getUserRole().toString().equals("USER"))  {
            menuUserProfile.setEnabled(false);
            menuLibrary.setEnabled(false);
            AuthorAddMenuItem.setEnabled(false);
            AuthorEditMenuItem.setEnabled(false);
            BookAddMenuItem.setEnabled(false);
            BookEditMenuItem.setEnabled(false);
        }
           
    }
}
