/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mylibraryapp.ui.form.book;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import mylibraryapp.domain.Author;
import mylibraryapp.domain.Book;
import mylibraryapp.service.BookService;
import mylibraryapp.service.impl.BookServiceImpl;
import mylibraryapp.ui.component.table.model.BookTableModel;
import mylibraryapp.ui.form.user.profile.UserProfileSearchForm;

/**
 *
 * @author Branislav Vujanov
 */
public class BookSearchForm extends javax.swing.JDialog {

    /**
     * Creates new form BookSearchForm
     */
    public BookSearchForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        pnlFilter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFilter3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled knjiga");

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBook);

        jLabel4.setText("Pretraga po kljucnoj reci:");

        txtFilter3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilter3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter3)
                .addContainerGap())
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFilter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        try {

            String authorName = "";
            int index = tblBook.convertRowIndexToModel​( tblBook.getSelectedRow());
            if (index != -1) {
                BookTableModel bookTableModel = (BookTableModel) tblBook.getModel();
                Book selectedBook = bookTableModel.getBook(index);
                List<Author> authors = selectedBook.getAuthors();
                for (Author author : authors) {

                    authorName = authorName + author.getFirstName() +" "+ author.getLastName() + "\n";
                }
                JOptionPane.showMessageDialog(this, authorName, "Autor(i): ", PLAIN_MESSAGE);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblBookMouseClicked

    private void txtFilter3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilter3KeyReleased
        String query = txtFilter3.getText();
        filter(query);
    }//GEN-LAST:event_txtFilter3KeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtFilter3;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            BookService bookService = new BookServiceImpl();
            TableModel model = new BookTableModel(bookService.getAll());
            tblBook.setModel(model);
            
            tblBook.setAutoCreateRowSorter(true);

            tblBook.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblBook.getColumnModel().getColumn(1).setPreferredWidth(350);
            tblBook.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblBook.getColumnModel().getColumn(3).setPreferredWidth(33);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            tblBook.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            tblBook.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            tblBook.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        } catch (Exception ex) {
            Logger.getLogger(UserProfileSearchForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    private void filter(String query){
        BookTableModel model =  (BookTableModel) tblBook.getModel();
        TableRowSorter<BookTableModel> tr = new TableRowSorter<>(model);
        tblBook.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }

}
