/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mylibraryapp.ui.form.author;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import mylibraryapp.domain.Author;
import mylibraryapp.domain.Book;
import mylibraryapp.service.BookService;
import mylibraryapp.service.impl.BookServiceImpl;
import mylibraryapp.ui.component.table.model.BookTableModel;
import mylibraryapp.ui.form.book.BookEditForm;

/**
 *
 * @author Branislav Vujanov
 */
public class AuthorDisplayForm extends javax.swing.JDialog {

    private final Author selectedAuthor;

    /**
     * Creates new form AuthorDisplayForm
     */
    public AuthorDisplayForm(java.awt.Frame parent, boolean modal, Author selectedAuthor) {
        super(parent, modal);
        initComponents();
        this.selectedAuthor = selectedAuthor;
        prepareViewe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled knjiga izabranog autora");

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBook);

        jLabel1.setText("Autor:");

        txtAuthor.setEditable(false);
        txtAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAuthor.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked

    }//GEN-LAST:event_tblBookMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtAuthor;
    // End of variables declaration//GEN-END:variables

    private void prepareViewe() {
        try {
            BookService bookService = new BookServiceImpl();
            List<Book> books = bookService.findBookByAuthor(selectedAuthor.getId());

            txtAuthor.setText(selectedAuthor.getFirstName() + " " + selectedAuthor.getLastName());
            TableModel model = new BookTableModel(books);
            tblBook.setModel(model);

            tblBook.setAutoCreateRowSorter(true);

            tblBook.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblBook.getColumnModel().getColumn(1).setPreferredWidth(350);
            tblBook.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblBook.getColumnModel().getColumn(3).setPreferredWidth(20);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            tblBook.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            tblBook.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            tblBook.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);

            

        } catch (Exception ex) {
            Logger.getLogger(BookEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
